# 指定服务名称
spring:
  profiles: 
    #active: server1
    active: server2
  application:
    name: eureka-server

# 指定主机地址
eureka:
  client:
    # 指定是否从注册中心获取服务(注册中心不需要开启)
    fetch-registry: false
    # 指定是否将服务注册到注册中心(注册中心不需要开启)
    register-with-eureka: true